name: CHAPERONg

dependencies:
  - main::python=3.8
# - anaconda::networkx=2.3
  - conda-forge::pymol-open-source=2.5.0
  - conda-forge::imagemagick
  - conda-forge::wxpython
  - conda-forge::ffmpeg
  - pip
  - pip:
    - scipy
    - pandas
    - numpy==1.23.4 # or 1.23.4>=numpy>=1.19.
# Numpy1.19 is the minimum required by matplotlib 
# Although Numpy versions 1.18.5 and 1.23.4 both
# worked with python 3.8.10, 3.8.13, 3.8.15, 3.8.16
    - matplotlib # tested versions: 3.6.1, 3.6.2, 3.6.3
    - networkx==2.3
    - biopandas
    - biopython
    - click
    - h5py>=3.0
    - mdtraj
    - plotly>=4.0
    - scikit-learn
    - toml
    - pmw
    - psutil              # required by plotly for png
    - openpyxl            # Required by pandas
    - md-davis
